# Form implementation generated from reading ui file 'gui/ui/studentTableWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(845, 82)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        mainWindow.setFont(font)
        mainWindow.setAutoFillBackground(False)
        mainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: rgb(22, 22, 22);\n"
"    font: 9pt \"Inter\";\n"
"}\n"
"\n"
"/* BUTTONS */\n"
"QPushButton {\n"
"    font: 9pt \"Inter\";\n"
"    font-weight: bold;\n"
"    padding: 0px, 15px;\n"
"    background-color: rgb(63, 150, 160);\n"
"    border-radius: 3px;\n"
"    padding: 0px 15px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: rgb(83, 170, 180);\n"
"}\n"
"\n"
"/* FRAMES */\n"
"QFrame {\n"
"  border: none;\n"
"}\n"
"\n"
"/* LABELS */\n"
"\n"
"#tableHeaderFrame QLabel {\n"
"    color: rgb(120, 139, 140);\n"
"}\n"
"\n"
"#dataFrame Line {\n"
"    background-color: rgb(120, 139, 140);\n"
"}")
        mainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(parent=mainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rowFrame_1 = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rowFrame_1.sizePolicy().hasHeightForWidth())
        self.rowFrame_1.setSizePolicy(sizePolicy)
        self.rowFrame_1.setMinimumSize(QtCore.QSize(0, 30))
        self.rowFrame_1.setMaximumSize(QtCore.QSize(16777215, 40))
        self.rowFrame_1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.rowFrame_1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.rowFrame_1.setObjectName("rowFrame_1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.rowFrame_1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.idNumber = QtWidgets.QLabel(parent=self.rowFrame_1)
        self.idNumber.setObjectName("idNumber")
        self.horizontalLayout_3.addWidget(self.idNumber)
        self.label = QtWidgets.QLabel(parent=self.rowFrame_1)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.label_6 = QtWidgets.QLabel(parent=self.rowFrame_1)
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.label_5 = QtWidgets.QLabel(parent=self.rowFrame_1)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(parent=self.rowFrame_1)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(parent=self.rowFrame_1)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.operationsFrame = QtWidgets.QFrame(parent=self.rowFrame_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.operationsFrame.sizePolicy().hasHeightForWidth())
        self.operationsFrame.setSizePolicy(sizePolicy)
        self.operationsFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.operationsFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.operationsFrame.setObjectName("operationsFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.operationsFrame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.operationsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_2.setStyleSheet("    background-color: rgb(63, 150, 160);\n"
"    border-radius: 3px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(parent=self.operationsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton.setStyleSheet("    background-color: rgb(63, 150, 160);\n"
"    border-radius: 3px;")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_3.addWidget(self.operationsFrame)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 2)
        self.horizontalLayout_3.setStretch(2, 1)
        self.horizontalLayout_3.setStretch(3, 1)
        self.horizontalLayout_3.setStretch(4, 1)
        self.horizontalLayout_3.setStretch(5, 1)
        self.horizontalLayout_3.setStretch(6, 1)
        self.verticalLayout.addWidget(self.rowFrame_1)
        self.line_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_2.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_2.setStyleSheet("background-color: rgb(120, 139, 140);\n"
"")
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.idNumber.setText(_translate("mainWindow", "2023-0001"))
        self.label.setText(_translate("mainWindow", "Kim Gabriel A. Nasayao"))
        self.label_6.setText(_translate("mainWindow", "Male"))
        self.label_5.setText(_translate("mainWindow", "2"))
        self.label_4.setText(_translate("mainWindow", "BSCS"))
        self.label_3.setText(_translate("mainWindow", "CCS"))
        self.pushButton_2.setText(_translate("mainWindow", "/"))
        self.pushButton.setText(_translate("mainWindow", "x"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec())
